# Generated by Django 5.1.6 on 2025-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
            ],
        ),
    ]
