# Generated by Django 5.1.2 on 2025-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ordered_number', models.PositiveIntegerField(default=0)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate as a percentage (e.g. 10 for 10%)', max_digits=5)),
                ('discount_start', models.DateTimeField(blank=True, null=True)),
                ('discount_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
