# Generated by Django 5.1.6 on 2025-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cover_image",
            field=models.ImageField(upload_to="book_covers/"),
        ),
    ]
