# Generated by Django 4.2.20 on 2025-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage off the base price (0–100)",
                max_digits=5,
            ),
        ),
    ]
